### ISSUE TITLE
Setup SWAGGER Github & Kanban

### ISSUE THREAD

**Issue by Kisgus** [SWAGGER-DAO/labs#1]
## 🎉   Subtasks

- [x] Connect to Zenhub
- [x] Invite members
- [x] Setup custom labels
- [x] Setup milestons for SWAGGER
- [x] Setup Team on Github
- [x] Setup issue template
- [x] Configure lines in Zenhub

## 🤼‍♂️   Reviewer

@frdrkhnssn @P3ter-NEARWEEK 

## 🔗   Work doc(s) / inspirational links

https://www.youtube.com/watch?v=Yb_RFA74_GY&t=81s

**Comment by Kisgus** [comment]
@frdrkhnssn @P3ter-NEARWEEK check-out issue....

**Comment by P3ter-NEARWEEK** [comment]
Looks good @Kisgus
